# Generated by Django 5.0.6 on 2024-05-28 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sexeduapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Laporan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('deskripsi', models.TextField()),
                ('waktu_laporan', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
