# Generated by Django 5.0.6 on 2024-05-28 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sexeduapp', '0002_laporan'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='laporan',
            table='laporan',
        ),
    ]
