# Generated by Django 5.0.6 on 2024-05-28 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sexeduapp', '0003_alter_laporan_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='laporan',
            name='waktu_laporan',
        ),
        migrations.AlterModelTable(
            name='laporan',
            table=None,
        ),
    ]
